---

- name: pull the {{ docker_image_tag }} image of microgateway
  shell: docker pull {{ docker_registry }}apic/microgateway:{{ docker_image_tag }}
  when: docker_registry != ""

- name: (re)start microgateway
  docker:
    name: microgateway
    image: "{{ docker_registry }}apic/microgateway:{{ docker_image_tag }}"
    state: reloaded
    restart_policy: "{{ docker.restart.policy }}"
    hostname: microgateway
    env:
      "GW_PORT": "{{ microgateway.port.gw }}"
      "MGMT_PORT": "{{ microgateway.port.mgmt }}"
      "EXT_HOST": "https://{{ groups['controllers']|first }}"
    ports:
      - "{{ microgateway.port.gw }}:4005"
      - "{{ microgateway.port.mgmt }}:3000"